Devel param
gfxdisp/FovVideoVDP pull request #4
Opened 2022-07-11 21:50 UTC by paramhanji

Some changes for Matlab <-> Python consistency

TODO:
- ex_foveated_video: Some restructuring needed (where to get display_model?); resizing uint16 requires cv2
- ex_hdr_images: library for HDR io (HDRutils?)

2022-07-12 17:13 UTC, mantiuk requested changes
A few minor issues. Perhaps one major issue is to make it clear that the examples should be run from the root of the repo:

python pytorch_examples/ex_aliasing.py

so that the paths will work.

2022-07-12 17:13 UTC, mantiuk commented on pytorch_examples/ex_blur_over_time.py
> +I_ref = utils.imread(os.path.join('..', 'matlab', 'examples', 'tree.jpg'))
Please move all example images and video to <root>/example_content/ instead of having them hidden in Matlab and python example directories.

2022-07-12 17:13 UTC, mantiuk commented on pytorch_examples/ex_simple_image.py
> +I_ref, I_test_noise, I_test_blur = utils.uint16to8((I_ref, I_test_noise, I_test_blur))
Perhaps you could cast to torch.int32 to maintain the precision?

2022-07-12 17:13 UTC, mantiuk commented on pytorch_examples/ex_utils.py
> +    dtype = clean.dtype
You could use https://numpy.org/doc/stable/reference/generated/numpy.iinfo.html instead of the "if" statements.

2022-07-13 11:04 UTC, paramhanji commented on pytorch_examples/ex_aliasing.py
> +sys.path.append('..')
I agree. Let's wait till I create the pip package to resolve this. The structure can be finalized at that time

2022-07-22 12:31 UTC, paramhanji commented
All the PyTorch examples are run directly by `python pytorch_examples/ex_*.py`. I do not think we need an explanation for each of them. We could mention this in the Readme, but the Readme shows the CLI version. Does it need to be updated?

2022-07-22 12:38 UTC, paramhanji commented
I've created the setup files for the pip package. Since I've given your email (https://github.com/gfxdisp/FovVideoVDP/blob/9b2098471c5888013cdbce4be8c237598ed6cab2/setup.py#L11), you will have to register and upload the package.

2022-08-03 14:25 UTC, paramhanji commented
TODO: update readme to show how to run PyTorch examples. Perhaps it is better to do this after cleanup.

2022-08-05 14:13 UTC, mantiuk approved these changes
All looks good.

2022-08-05 14:13 UTC, merged